from .user import get_main_keyboard, get_back_keyboard, get_pagination_keyboard
from .admin import get_admin_panel_keyboard, get_role_simulation_keyboard, get_broadcast_menu_keyboard, get_broadcast_confirm_keyboard, get_generate_code_plans_keyboard, get_custom_duration_type_keyboard
from .dev import get_dev_panel_keyboard, get_devlog_dates_keyboard, get_devlog_message_keyboard, get_maintenance_keyboard, get_maintenance_confirm_keyboard
from .subscription import get_subscription_keyboard, get_redeem_retry_keyboard, get_crypto_plans_keyboard, get_crypto_currencies_keyboard, get_payment_status_keyboard
from .orders import get_user_orders_keyboard, get_user_order_view_keyboard, get_admin_orders_menu_keyboard, get_admin_orders_list_keyboard, get_admin_order_view_keyboard